#spring.application.name=banking-api


## LOCAL ORACLE DATABASE CONFIGURATION
##spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
##spring.datasource.username=BANK_ADMIN
##spring.datasource.password=bank123
##spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
## CLOUD ORACLE CONFIG
#
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
##oracle.net.tns_admin=src/main/resources/wallet
#oracle.net.tns_admin=/app/wallet
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always
#management.endpoint.health.probes.enabled=true
#
## management.server.port=${PORT:8080}
#management.endpoints.web.base-path=/actuator
#


# spring.profiles.active=dev
spring.profiles.active=prod
