spring.application.name=banking-api

# LOCAL ORACLE DATABASE CONFIGURATION
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
#spring.datasource.username=BANK_ADMIN
#spring.datasource.password=bank123
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CLOUD ORACLE CONFIG
spring.datasource.url=jdbc:oracle:thin:@bankingdb_high
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
oracle.net.tns_admin=src/main/resources/wallet

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true